server:
  port: 9090
jwt:
  secret: Y29tLnBhdWxoYW4uand0LnByYWN0aWNlLm9uZW1vcmU=
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: jd
    password: jd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

  jpa:
    generate-ddl: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
    
file:
  dir: C:/justdo_file/

