server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@220.85.6.86:50256:xe
    username: jd
    password: jd
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
<<<<<<< HEAD
    hibernate:
      ddl-auto: create
=======
    #hibernate:
      #ddl-auto: create
>>>>>>> e260d342a235077d3c50828917766839341e4541
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
  